spring:
  application:
    name: itoken-config
  boot:
    admin:
      client:
        url: http://39.106.24.18:8084
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/13669005514/spring-cloud-config
          search-paths: respo
          username:
          password:
  zipkin:
    base-url: http://39.106.24.18:9411

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://39.106.24.18:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info